const main = document.querySelector('#main');
function home(){phase='home';main.innerHTML=`<section class="hero enter"><div class="hero-copy"><p class="eyebrow">MADRID · TRES FORMAS DE VIVIR LA TARDE</p><p class="prize-hook">PREMIO ASEGURADO</p><h1>¿QUÉ<br>TARDEO <em>ERES?</em></h1><p class="intro">Descubre tu tardeo y consigue un <strong>50% de descuento para el próximo fin de semana.</strong></p><button class="primary" id="start">Encontrar mi tardeo <span class="arrow" aria-hidden="true">↗</span></button><p class="micro">3 PREGUNTAS · 30 SEGUNDOS · PREMIO ASEGURADO</p></div><figure class="hero-art"><div class="photo-frame"><img src="${escapeHtml(config.portada.image)}" alt="${escapeHtml(config.portada.alt)}" width="1200" height="800" fetchpriority="high"></div><figcaption class="photo-caption"><span>LA VIDA ES HOY. LA VIDA ES RITA.</span><span>MADRID ↗</span></figcaption><span class="photo-label">Nos vemos bailando.</span><span class="hero-reward"><strong>50%</strong><span>DE DESCUENTO</span><small>Tu próximo finde</small></span></figure></section><div class="ticker"><span>Buena música</span><b aria-hidden="true">✳</b><span>Mejor compañía</span><b aria-hidden="true">✳</b><span>Tu próximo plan</span></div><section class="home-brands"><div class="section-heading"><p class="eyebrow">ELIGE CON EL CORAZÓN. O DEJA QUE LO HAGA EL TEST.</p><h2>Tres tardeos.<br><em>Muchas ganas de verte.</em></h2></div><div class="lineup" aria-label="Los tres tardeos">${['despecha','rita','duende'].map((id,i)=>`<article class="brand-mini ${id}"><img src="${escapeHtml(config[id].image)}" alt="${escapeHtml(config[id].alt)}" loading="lazy" width="600" height="400"><div class="mini-copy"><span class="mini-number">0${i+1}</span><h3>${brands[id].name}</h3><p>${id==='despecha'?'PONZANO · COMERCIAL & HITS':id==='rita'?'BONDED · TARDEO & HITS':'MAMAO · FLAMENCO Y URBAN HITS'}</p><a class="instagram" href="https://www.instagram.com/${brands[id].instagram}/" target="_blank" rel="noopener noreferrer">@${brands[id].instagram} ↗</a></div></article>`).join('')}</div></section>`;document.querySelector('#start').onclick=startQuiz;}
const config = window.TARDEO_CONFIG;
const brands = {
 despecha: {name:'La Despechá',instagram:'ladespecha.madrid',venue:'La Despechá · Ponzano',address:'C. Santísima Trinidad 34, Madrid',displayAddress:'C. Santísima Trinidad 34, Ponzano',diagnosis:'Tú no sales «a tomar algo». Tú sales a darlo todo.',description:'Suena un temazo comercial y ya estás en primera fila. Lo tuyo son los flashes, el baile sin pausa y cantar ese tema como si fuera para tu ex.',tags:['Comercial & hits','Flashes','Cero timidez'],poster:'LA<br>DESPECHÁ',teaser:'Temazos comerciales, cero vergüenza y la última que nunca llega.'},
 rita: {name:'Rita la Bailaora',instagram:'ritalabailaoramadrid',venue:'Rita la Bailaora · Bonded',address:'C. Miguel Ángel 9, Madrid',displayAddress:'C. Miguel Ángel 9',diagnosis:'Llegas con estilo. Te vas sin voz.',description:'Tu plan lleva buena compañía, canciones que os sabéis de memoria y ese punto mediterráneo que convierte una tarde cualquiera en una celebración.',tags:['Tardeo & hits','Aire mediterráneo','Con mucho arte'],poster:'Rita<br>la Bailaora',teaser:'Hits, elegancia y ese «una más» con tus amigas.'},
 duende: {name:'Tardeo Duende',instagram:'duende.tardeo',venue:'Tardeo Duende · Sala MAMAO',address:'C. Alberto Alcocer 48, Madrid',displayAddress:'C. Alberto Alcocer 48',diagnosis:'Lo tuyo no se explica. Se lleva dentro.',description:'Te arrancas con unas palmas y el resto viene solo. Flamenco y urban hits, mucho compás y una tarde para dejar que hable tu duende.',tags:['Flamenco y urban hits','Palmas arriba','Mucho compás'],poster:'TARDEO<br>DUENDE',teaser:'Del «olé» al urban hit. Aquí se viene a romper la tarde.'}
};
const questions = [
 {title:'Son las 19:00. ¿Cómo vas?',note:'Acabas de llegar. De momento, todo bajo control.',answers:[['despecha','Buscando la pista. He venido a liarla.'],['rita','Con un lookazo y mi gente favorita.'],['duende','Con ganas de palmas y mucho arte.']]},
 {title:'Suena TU canción. ¿Qué pasa?',note:'Da igual lo que estuvieras contando.',answers:[['rita','Abrazo a mis amigas. Este es NUESTRO tema.'],['duende','Me arranco. Las palmas salen solas.'],['despecha','Bajo hasta el suelo. Sin más preguntas.']]},
 {title:'Una última: ¿con qué te quedas?',note:'Haz caso a tu primer impulso.',answers:[['despecha','Con esos temazos comerciales que me sé enteros.'],['duende','Con flamenco y urban hits. Sin elegir bando.'],['rita','Con un hit cantado a pleno pulmón.']]}
];
let current = 0, answers = [], winner = null, phase = 'home', timers = [], guestName = ''; 
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));}
function clearTimers(){timers.forEach(clearTimeout);timers=[];}
function focusView(){window.scrollTo({top:0,behavior:'instant'});main.focus({preventScroll:true});}
function startQuiz(){clearTimers();current=0;answers=[];winner=null;guestName='';phase='quiz';renderQuestion();}
function renderQuestion(){
 clearTimers();const q=questions[current]; phase='quiz';
 main.innerHTML=`<section class="quiz-shell enter"><div class="quiz-meta"><button class="text-button" id="back">← ${current?'Anterior':'Portada'}</button><span>Pregunta ${current+1} de ${questions.length}</span></div><div class="progress" role="progressbar" aria-label="Preguntas contestadas" aria-valuemin="0" aria-valuemax="${questions.length}" aria-valuenow="${current}"><i style="width:${current/questions.length*100}%"></i></div><p class="eyebrow">SIN PENSARLO DEMASIADO</p><h1 class="question-title" id="question">${q.title}</h1><p class="question-note">${q.note}</p><div class="answers" role="group" aria-labelledby="question">${q.answers.map(([id,label],index)=>`<button class="answer" data-answer="${id}" aria-pressed="${answers[current]===id}"><span class="answer-letter" aria-hidden="true">${'ABC'[index]}</span><span>${label}</span></button>`).join('')}</div><p class="answer-hint">Elige la que más va contigo. Y seguimos ↗</p></section>`;
 document.querySelectorAll('[data-answer]').forEach(button=>button.onclick=()=>chooseAnswer(button.dataset.answer));
 document.querySelector('#back').onclick=()=>{clearTimers();if(current){current--;renderQuestion();}else{phase='home';home();focusView();}};
 focusView();
}
function selectAnswer(id){if(phase!=='quiz'||!questions[current].answers.some(a=>a[0]===id))throw new Error('Respuesta no válida');answers[current]=id;document.querySelectorAll('[data-answer]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.answer===id)));}
function chooseAnswer(id){
 if(phase!=='quiz')return;
 selectAnswer(id);phase='transition';
 document.querySelectorAll('[data-answer]').forEach(button=>button.disabled=true);
 timers.push(setTimeout(()=>{phase='quiz';advance();},260));
}
function pickWinner(selected){const scores={despecha:0,rita:0,duende:0};selected.forEach(id=>scores[id]++);const best=Math.max(...Object.values(scores));return [...selected].reverse().find(id=>scores[id]===best);}
function advance(){if(phase!=='quiz'||!answers[current])return;if(current<questions.length-1){current++;renderQuestion();}else{winner=pickWinner(answers);showName();}}
function analyse(){phase='analysis';clearTimers();main.innerHTML=`<section class="analysis enter"><div class="spinner" aria-hidden="true"></div><h1>Analizando tu<br>nivel de tardeo…</h1><p id="analysis-copy" role="status">Midiendo tus ganas de liarla.</p><p class="micro">UN DIAGNÓSTICO POCO CIENTÍFICO. MUY TUYO.</p></section>`;focusView();timers.push(setTimeout(()=>{document.querySelector('#analysis-copy').textContent='Cruzando temazos con pasos prohibidos…';},550));timers.push(setTimeout(()=>{document.querySelector('#analysis-copy').textContent='Ya sabemos dónde vas a darlo todo.';},1050));timers.push(setTimeout(()=>showResult(winner,true),2500));}
function showName(){
 phase='name';main.innerHTML=`<section class="quiz-shell name-step enter"><p class="eyebrow">YA TENEMOS TU MATCH.</p><h1 class="question-title">Las buenas tardes<br><em>llevan tu nombre.</em></h1><p class="question-note">Tu tardeo está decidido. Pon tu nombre y descubre tu resultado con premio.</p><form id="name-form"><label for="guest-name">¿Cómo te llamas?</label><input id="guest-name" name="name" type="text" autocomplete="given-name" maxlength="40" required placeholder="Tu nombre" aria-describedby="name-note name-error"><p id="name-note" class="micro">Solo para tu tarjeta. No guardamos tu nombre.</p><p id="name-error" role="alert"></p><button class="primary next" type="submit">Descubrir mi premio <span aria-hidden="true">↗</span></button></form><button id="edit-answer" class="text-button">← Cambiar mi última respuesta</button></section>`;
 document.querySelector('#name-form').onsubmit=e=>{e.preventDefault();const value=document.querySelector('#guest-name').value.trim().replace(/\s+/g,' ');if(!value){document.querySelector('#name-error').textContent='Pon tu nombre para preparar tu tarjeta.';document.querySelector('#guest-name').focus();return;}guestName=value.slice(0,40);analyse();};
 document.querySelector('#edit-answer').onclick=()=>{current=questions.length-1;renderQuestion();};focusView();
}
function showResult(id,isMatch=id===winner){
 if(!brands[id])throw new Error('Tardeo no válido');clearTimers();phase='result';const b=brands[id],c=config[id];const others=Object.keys(brands).filter(key=>key!==id);const map='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(b.address);let url=map;try{const custom=new URL(c.ctaUrl);if(custom.protocol==='https:')url=custom.href;}catch{}
 const insta='https://www.instagram.com/'+b.instagram+'/';
 const prize=`<section class="prize-section" aria-label="Tu premio: 50% de descuento"><div class="prize-ticket" id="prize-ticket"><div class="ticket-top"><span>PREMIO ASEGURADO</span><span>PARA EL PRÓXIMO FIN DE SEMANA ↗</span></div><h2>50% de descuento</h2><p class="prize-greeting">${guestName?`${escapeHtml(guestName)}, tu`: 'Tu'} próximo plan tiene premio.</p><p class="discount-label">TU CÓDIGO</p><strong class="discount-code">DESCUENTO50</strong><p class="ticket-bottom">Utiliza DESCUENTO50 para disfrutar de un 50% de descuento el próximo fin de semana en ${b.name}.</p></div></section>`;
 main.innerHTML=`<section class="result-page ${id} enter"><header class="result-heading"><p class="eyebrow">${isMatch?'TU MATCH PARA ESTA TARDE':'OTRA FORMA DE LIARTE'}</p><h1 class="result-title">${b.name}</h1></header>${prize}<div class="others"><h2>Tu código también tiene otros planes.</h2><p>El código <strong>DESCUENTO50</strong> también se puede utilizar en estos tardeos: <strong>50% de descuento para el próximo fin de semana.</strong> Elige dónde quieres vivir tu próxima gran tarde.</p><div class="other-grid">${others.map(key=>`<article class="other-card"><img class="other-photo" src="${escapeHtml(config[key].image)}" alt="${escapeHtml(config[key].alt)}" loading="lazy" width="600" height="400"><h3>${brands[key].name}</h3><a class="instagram" href="https://www.instagram.com/${brands[key].instagram}/" target="_blank" rel="noopener noreferrer">@${brands[key].instagram} ↗</a><p>${brands[key].teaser}</p><p>${brands[key].venue}<br>${brands[key].displayAddress}</p><button class="text-button" data-brand="${key}">Descubrir este tardeo ↗</button></article>`).join('')}</div>${!isMatch&&winner?'<button class="text-button restart" id="match">Volver a mi resultado y mi premio</button>':''}<button class="text-button restart" id="restart">Volver a jugar ↻</button></div><div class="result-main"><div><a class="instagram" href="${insta}" target="_blank" rel="noopener noreferrer">@${b.instagram} ↗</a><p class="diagnosis">${b.diagnosis}</p><p class="result-description">${b.description}</p><div class="tags">${b.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div></div><div class="result-visual"><img src="${escapeHtml(c.image)}" alt="${escapeHtml(c.alt)}" width="768" height="1024"><span class="image-caption">${b.name}</span></div></div><section class="venue-gallery" aria-label="Fotos de ${b.name}"><div class="gallery-heading"><p class="eyebrow">ASÍ SE VIVE ${b.name.toUpperCase()}</p><h2>Te guardamos <em>un hueco.</em></h2></div><div class="gallery-grid">${c.gallery.map(photo=>`<figure><img src="${escapeHtml(photo.image)}" alt="${escapeHtml(photo.alt)}" width="1200" height="800" loading="lazy"><figcaption>${photo.caption}</figcaption></figure>`).join('')}</div></section><div class="result-location"><div class="location"><strong>${b.venue}</strong>${b.displayAddress} · Madrid</div><a class="text-button map-link" href="${escapeHtml(url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(c.ctaLabel)} ↗</a></div></section>`;
 document.querySelectorAll('[data-brand]').forEach(button=>button.onclick=()=>showResult(button.dataset.brand));document.querySelector('#restart').onclick=startQuiz;const match=document.querySelector('#match');if(match)match.onclick=()=>showResult(winner,true);focusView();
}
// Mejora opcional: herramientas de navegador. Los navegadores sin soporte mantienen el quiz completo.
if(document.modelContext?.registerTool){const lifecycle=new AbortController();const definitions=[{name:'start_tardeo_quiz',description:'Empieza o reinicia el quiz visible de tres preguntas.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute(){startQuiz();return {question:current+1,title:questions[current].title,options:questions[current].answers};}},{name:'answer_tardeo_question',description:'Selecciona una respuesta de la pregunta actual y avanza; la última abre el formulario de nombre para la tarjeta de premio.',inputSchema:{type:'object',properties:{answer:{type:'string',enum:['despecha','rita','duende']}},required:['answer'],additionalProperties:false},async execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>k!=='answer'))throw new Error('Entrada no válida');selectAnswer(input.answer);advance();if(phase==='analysis')await new Promise(resolve=>setTimeout(resolve,2600));return phase==='name'?{step:'name',message:'Escribe tu nombre en el formulario visible para ver el resultado y el premio.'}:phase==='result'?{result:winner,name:brands[winner].name}:{question:current+1,title:questions[current].title,options:questions[current].answers};}}];for(const tool of definitions){try{Promise.resolve(document.modelContext.registerTool({...tool,annotations:{readOnlyHint:false,untrustedContentHint:false}},{signal:lifecycle.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
home();
