const main = document.querySelector('#main');
function home(){main.innerHTML = `<section class="hero enter"><div><p class="eyebrow">TRES PLANES. UNA SOLA ACTITUD.</p><h1>¿QUÉ<br>TARDEO<br><em>eres?</em></h1><p class="intro">Dices «una y me voy».<br>Pero tu tardeo dice otra cosa.</p><button class="primary" id="start">Descubrir mi tardeo <span class="arrow" aria-hidden="true">↗</span></button><p class="micro">3 PREGUNTAS · 30 SEGUNDOS · CERO JUICIOS</p></div><div class="hero-art" aria-label="Ambiente de fiesta, imagen ilustrativa"><div class="photo-frame"><img src="${escapeHtml(config.portada.image)}" alt="${escapeHtml(config.portada.alt)}" width="768" height="1024" fetchpriority="high"></div><div class="photo-caption"><span>UN PLAN TRANQUILO, DECÍAS.</span><span>MADRID ↗</span></div><div class="sticker" aria-hidden="true">PELIGRO DE<strong>LIARTE</strong>ESTA TARDE</div><span class="photo-label">la noche puede esperar.</span></div></section><div class="ticker" aria-hidden="true"><span>UN POCO DE DESPECHO</span><b>✳</b><span>MUCHO BAILE</span><b>✳</b><span>TODO EL DUENDE</span></div><section class="lineup" aria-label="Los tres tardeos"><div class="brand-mini"><div><strong>LA DESPECHÁ</strong><small>PONZANO · REGUETÓN</small></div><span>01</span></div><div class="brand-mini"><div><strong>RITA LA BAILAORA</strong><small>BONDED · TARDEO & HITS</small></div><span>02</span></div><div class="brand-mini"><div><strong>TARDEO DUENDE</strong><small>MAMAO · FLAMENCO CONTEMPORÁNEO</small></div><span>03</span></div></section>`;document.querySelector('#start').onclick=()=>startQuiz();}
const config = window.TARDEO_CONFIG;
const brands = {
 despecha: {name:'La Despechá',venue:'La Despechá · Ponzano',address:'C. Santísima Trinidad 34, Madrid',displayAddress:'C. Santísima Trinidad 34, Ponzano',diagnosis:'Tú no sales «a tomar algo». Tú sales a darlo todo.',description:'Un estribillo de reguetón y ya estás en primera fila. Lo tuyo son los flashes, el baile sin pausa y cantar ese tema como si fuera para tu ex.',tags:['Reguetón','Flashes','Cero timidez'],poster:'LA<br>DESPECHÁ',teaser:'Despecho, reguetón y ganas de no mirar el reloj.'},
 rita: {name:'Rita la Bailaora',venue:'Rita la Bailaora · Bonded',address:'C. Miguel Ángel 9, Madrid',displayAddress:'C. Miguel Ángel 9',diagnosis:'Llegas con estilo. Te vas sin voz.',description:'Tu plan lleva buena compañía, canciones que os sabéis de memoria y ese punto mediterráneo que convierte una tarde cualquiera en una celebración.',tags:['Tardeo & hits','Aire mediterráneo','Con mucho arte'],poster:'Rita<br>la Bailaora',teaser:'Hits, elegancia y ese «una más» con tus amigas.'},
 duende: {name:'Tardeo Duende',venue:'Tardeo Duende · Sala MAMAO',address:'C. Alberto Alcocer 48, Madrid',displayAddress:'C. Alberto Alcocer 48',diagnosis:'Lo tuyo no se explica. Se lleva dentro.',description:'Te arrancas con unas palmas y el resto viene solo. Flamenco contemporáneo, mucho compás y una tarde para dejar que hable tu duende.',tags:['Flamenco contemporáneo','Palmas arriba','Mucho compás'],poster:'TARDEO<br>DUENDE',teaser:'Flamenco con otro aire. El compás lo pones tú.'}
};
const questions = [
 {title:'Son las 19:00. ¿Cómo vas?',note:'Acabas de llegar. De momento, todo bajo control.',answers:[['despecha','Buscando la pista. He venido a perrear.'],['rita','Con un lookazo y mi gente favorita.'],['duende','Con ganas de palmas y mucho arte.']]},
 {title:'Suena TU canción. ¿Qué pasa?',note:'Da igual lo que estuvieras contando.',answers:[['rita','Abrazo a mis amigas. Este es NUESTRO tema.'],['duende','Me arranco. Las palmas salen solas.'],['despecha','Bajo hasta el suelo. Sin más preguntas.']]},
 {title:'Una última: ¿con qué te quedas?',note:'Haz caso a tu primer impulso.',answers:[['despecha','Con ese reguetón que me sé de principio a fin.'],['duende','Con una mezcla de flamenco y algo inesperado.'],['rita','Con un hit cantado a pleno pulmón.']]}
];
let current = 0, answers = [], winner = null, phase = 'home', timers = [];
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));}
function clearTimers(){timers.forEach(clearTimeout);timers=[];}
function focusView(){window.scrollTo({top:0,behavior:'instant'});main.focus({preventScroll:true});}
function startQuiz(){clearTimers();current=0;answers=[];winner=null;phase='quiz';renderQuestion();}
function renderQuestion(){
 const q=questions[current]; phase='quiz';
 main.innerHTML=`<section class="quiz-shell enter"><div class="quiz-meta"><button class="text-button" id="back">← ${current?'Anterior':'Portada'}</button><span>Pregunta ${current+1} de ${questions.length}</span></div><div class="progress" role="progressbar" aria-label="Preguntas contestadas" aria-valuemin="0" aria-valuemax="${questions.length}" aria-valuenow="${current}"><i style="width:${current/questions.length*100}%"></i></div><p class="eyebrow">SIN PENSARLO DEMASIADO</p><h1 class="question-title" id="question">${q.title}</h1><p class="question-note">${q.note}</p><div class="answers" role="group" aria-labelledby="question">${q.answers.map(([id,label],index)=>`<button class="answer" data-answer="${id}" aria-pressed="${answers[current]===id}"><span class="answer-letter" aria-hidden="true">${'ABC'[index]}</span><span>${label}</span></button>`).join('')}</div><button class="primary next" id="next" ${answers[current]?'':'disabled'}>${current===questions.length-1?'Ver mi resultado':'Siguiente'}<span aria-hidden="true">→</span></button></section>`;
 document.querySelectorAll('[data-answer]').forEach(button=>button.onclick=()=>selectAnswer(button.dataset.answer));
 document.querySelector('#next').onclick=()=>advance();
 document.querySelector('#back').onclick=()=>{if(current){current--;renderQuestion();}else{phase='home';home();focusView();}};
 focusView();
}
function selectAnswer(id){if(phase!=='quiz'||!questions[current].answers.some(a=>a[0]===id))throw new Error('Respuesta no válida');answers[current]=id;document.querySelectorAll('[data-answer]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.answer===id)));document.querySelector('#next').disabled=false;}
function pickWinner(selected){const scores={despecha:0,rita:0,duende:0};selected.forEach(id=>scores[id]++);const best=Math.max(...Object.values(scores));return [...selected].reverse().find(id=>scores[id]===best);}
function advance(){if(phase!=='quiz'||!answers[current])return;if(current<questions.length-1){current++;renderQuestion();}else{winner=pickWinner(answers);analyse();}}
function analyse(){phase='analysis';clearTimers();main.innerHTML=`<section class="analysis enter"><div class="spinner" aria-hidden="true"></div><h1>Analizando tu<br>nivel de tardeo…</h1><p id="analysis-copy" role="status">Midiendo tus ganas de liarla.</p><p class="micro">UN DIAGNÓSTICO POCO CIENTÍFICO. MUY TUYO.</p></section>`;focusView();timers.push(setTimeout(()=>{document.querySelector('#analysis-copy').textContent='Cruzando temazos con pasos prohibidos…';},850));timers.push(setTimeout(()=>{document.querySelector('#analysis-copy').textContent='Ya sabemos dónde vas a darlo todo.';},1700));timers.push(setTimeout(()=>showResult(winner,true),2500));}
function showResult(id,isMatch=id===winner){
 if(!brands[id])throw new Error('Tardeo no válido');clearTimers();phase='result';const b=brands[id],c=config[id];const others=Object.keys(brands).filter(key=>key!==id);const map='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(b.address);let url=map;try{const custom=new URL(c.ctaUrl);if(custom.protocol==='https:')url=custom.href;}catch{}
 main.innerHTML=`<section class="result-page ${id} enter"><div class="result-main"><div><p class="eyebrow">${isMatch?'TU TARDEO TIENE NOMBRE':'OTRA FORMA DE LIARTE'}</p><h1 class="result-title">${b.name}</h1><p class="diagnosis">${b.diagnosis}</p><p class="result-description">${b.description}</p><div class="tags">${b.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="location"><strong>${b.venue}</strong>${b.displayAddress}<br>Madrid</div><a class="primary" href="${escapeHtml(url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(c.ctaLabel)}<span aria-hidden="true">↗</span></a></div><div class="result-visual"><img src="${escapeHtml(c.image)}" alt="${escapeHtml(c.alt)}" width="768" height="1024"><div class="brand-poster" aria-hidden="true">${b.poster}</div></div></div><div class="others"><h2>También tienes estas dos tentaciones.</h2><p>Porque tu próxima tarde puede tener otro ritmo.</p><div class="other-grid">${others.map(key=>`<button class="other-card" data-brand="${key}"><h3>${brands[key].name}</h3><p>${brands[key].teaser}</p><p>${brands[key].venue}<br>${brands[key].displayAddress}</p><span>Descubrir este tardeo ↗</span></button>`).join('')}</div>${!isMatch&&winner?'<button class="text-button restart" id="match">Volver a mi resultado</button>':''}<button class="text-button restart" id="restart">Volver a jugar ↻</button></div></section>`;
 document.querySelectorAll('[data-brand]').forEach(button=>button.onclick=()=>showResult(button.dataset.brand));document.querySelector('#restart').onclick=startQuiz;const match=document.querySelector('#match');if(match)match.onclick=()=>showResult(winner,true);focusView();
}
// Mejora opcional: herramientas de navegador. Los navegadores sin soporte mantienen el quiz completo.
if(document.modelContext?.registerTool){const lifecycle=new AbortController();const definitions=[{name:'start_tardeo_quiz',description:'Empieza o reinicia el quiz visible de tres preguntas.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute(){startQuiz();return {question:current+1,title:questions[current].title,options:questions[current].answers};}},{name:'answer_tardeo_question',description:'Selecciona una respuesta de la pregunta actual y avanza; la última muestra el análisis y el resultado.',inputSchema:{type:'object',properties:{answer:{type:'string',enum:['despecha','rita','duende']}},required:['answer'],additionalProperties:false},async execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>k!=='answer'))throw new Error('Entrada no válida');selectAnswer(input.answer);advance();if(phase==='analysis')await new Promise(resolve=>setTimeout(resolve,2600));return phase==='result'?{result:winner,name:brands[winner].name}:{question:current+1,title:questions[current].title,options:questions[current].answers};}}];for(const tool of definitions){try{Promise.resolve(document.modelContext.registerTool({...tool,annotations:{readOnlyHint:false,untrustedContentHint:false}},{signal:lifecycle.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
home();
